# Generated by Django 3.1 on 2020-09-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/default.jpg', null=True, upload_to='img'),
        ),
    ]
